INSERT INTO BUILDING(ID, NAME) VALUES (-1, 'Test Building 1');
INSERT INTO BUILDING(ID, NAME) VALUES (-2, 'Test Building 2');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1.1', 1, -1);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room1.2', 1, -1);

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-11, 'Room2.1', 1, -2);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-12, 'Room2.2', 2, -2);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -11);
