INSERT INTO DEVICE_GROUP(ID, NAME) VALUES (-1, 'Test Group');

--INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID, STATUS) VALUES (-10, 'Room1.1', 1, -1, 'OFF');
--INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID, STATUS) VALUES (-9,  'Room1.2', 1, -1, 'OFF');
--
--INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID, STATUS) VALUES (-11, 'Room2.1', 1, -2, 'OFF');
--INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID, STATUS) VALUES (-12, 'Room2.2', 2, -2, 'OFF');
--
--INSERT INTO COLOR(ID, HUE, SATURATION, VALUE, ARGB) VALUES (-1, 0, 0, 1, -1);
--INSERT INTO LIGHT(ID, LEVEL, STATUS, CONNECTED, COLOR_ID) VALUES (-1, 8, 'OFF', false, -1);
--
--INSERT INTO COLOR(ID, HUE, SATURATION, VALUE, ARGB) VALUES (-2, 0, 0, 1, -1);
--INSERT INTO LIGHT(ID, LEVEL, STATUS, CONNECTED, ROOM_ID, COLOR_ID) VALUES (-2, 0, 'OFF', false, -10, -2);
--
--INSERT INTO COLOR(ID, HUE, SATURATION, VALUE, ARGB) VALUES (-3, 0, 0, 1, -1);
--INSERT INTO LIGHT(ID, LEVEL, STATUS, CONNECTED, ROOM_ID, COLOR_ID) VALUES (-3, 8, 'OFF', false, -11, -3);
